# Generated by Django 5.0.2 on 2024-03-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("date_hadis", "0002_remove_post_blocks_alter_post_date_block_post_rel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="D:\\Project\\core_app\\media/block_images/",
            ),
        ),
        migrations.AlterField(
            model_name="block_post_rel",
            name="order",
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
