# Generated by Django 5.0.2 on 2024-03-04 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("date_hadis", "0003_alter_block_image_alter_block_post_rel_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="block",
            options={
                "verbose_name": "Content Block",
                "verbose_name_plural": "Content Blocks",
            },
        ),
        migrations.AlterModelOptions(
            name="block_post_rel",
            options={
                "ordering": ["post", "order"],
                "verbose_name": "Post Content Relation",
                "verbose_name_plural": "Post Content Relations",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "Post", "verbose_name_plural": "Posts"},
        ),
        migrations.AlterField(
            model_name="block",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="D:\\Project\\core_app\\media/block_images/",
                verbose_name="Block Image",
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Block Text"),
        ),
        migrations.AlterField(
            model_name="block",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="Block URL"),
        ),
        migrations.AlterField(
            model_name="block_post_rel",
            name="block",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="date_hadis.block",
                verbose_name="Content Block",
            ),
        ),
        migrations.AlterField(
            model_name="block_post_rel",
            name="order",
            field=models.PositiveIntegerField(
                editable=False, verbose_name="Block Order"
            ),
        ),
        migrations.AlterField(
            model_name="block_post_rel",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="date_hadis.post",
                verbose_name="Post",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateField(unique=True, verbose_name="Post Date"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=30, verbose_name="Post Title"),
        ),
    ]
