# Generated by Django 5.0.2 on 2024-03-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "date_hadis",
            "0004_alter_block_options_alter_block_post_rel_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title_en",
            field=models.CharField(max_length=30, null=True, verbose_name="Post Title"),
        ),
        migrations.AddField(
            model_name="post",
            name="title_tr",
            field=models.CharField(max_length=30, null=True, verbose_name="Post Title"),
        ),
    ]
