# Generated by Django 5.0.2 on 2024-03-04 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("date_hadis", "0005_post_title_en_post_title_tr"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="title_tr",
            new_name="title_ur",
        ),
    ]
