# Generated by Django 5.0.2 on 2024-03-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("date_hadis", "0007_block_text_en_block_text_ur"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="D:\\Project\\core_app\\media/post_images/",
                verbose_name="Post Image",
            ),
        ),
    ]
